export const popItems = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Peach Bellini Herbal Tea",
    price: "$6.99",
    desc: "Sip and have some fun.",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Creme Brulee Earl Grey Black Tea",
    price: "$6.99",
    desc: "Creamy and delicious Earl Grey",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "The self care blend",
    price: "$6.99",
    desc: "Feel cared for and looked after with this healing blend.",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Lightly sweet & spiced, full of love.",
    price: "$6.99",
    desc: "Sip and have some fun.",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Treat yourself with a delish cookie in a cup.",
    price: "$6.99",
    desc: "Sip and have some fun.",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Chocolate Caramel Macadamia Nut Herbal Tea",
    price: "$7.99",
    desc: "A distinctively enjoyable delight.",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Chocolate Hazlenut Chai",
    price: "$8.99",
    desc: "Sweet and spicy and delicious limited-edition chocolate chai.",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Chocolate Hazelnut Dessert Tea",
    price: "$9.99",
    desc: "Chocolate + hazelnut are the perfect pairing, even in tea.",
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Cinny Roll Black Tea",
    price: "$16.99",
    desc: "Rich cinnamon, sweet cream, taking time to savor the moment",
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/5946751/pexels-photo-5946751.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Citrus Mint Green Tea",
    price: "$14.99",
    desc: "Sit In The Stillness and Feel Refreshed.",
  },
];
